version: '2'
services:
    epdk-app:
        image: epdk
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://epdk-mssql:1433;database=EPDK
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    epdk-mssql:
        extends:
            file: mssql.yml
            service: epdk-mssql
